### ISSUE TITLE
Beautiful design 

### ISSUE THREAD

**Issue by jwang-lilly** [themefisher/bigspring-light-nextjs#1]
Hi, 

I just started using nextjs and came across your repo.

I really like the clean beautiful design.  Thanks for making the fantastic resources free to the community.  Great job!

I just have one issue with the way Base from Baseoff.js is used.  I see you import it into each page individually, for [regular].js,  index.js, 404.js, or those blog pages.  Actually, you could make it simple by importing it into _app.js file.  Let it wraps around the <Component {...pageProps} />.  That way, you once need to once and the nav bar, menus and footer would automatically show up on all pages.

Making sense?

It would also be really helpful if you could provide documentation for the demo app.

**Comment by tfsomrat** [comment]
Hello @JianWang2016 

Thanks for your feedback. We did it for a reason. Sometimes we need to pass different values to the baseof file for SEO terms. and call baseof on every file is not that hard. 

We are building Nextjs templates like months ago. we are trying to build a common format for every template, then we will add a guide/documentation about how to use our products. 

I appreciate your comment and hope I'll get more feedback from you. so we can improve our product at the best. thanks a lot.
